name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_WORKSPACE: /build
    container:
      image: ghcr.io/anyakichi/poetry-builder:3.9
      volumes:
        - /build
      options: -w /build
    steps:
      - uses: actions/checkout@v2
      - run: pwd
