name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/anyakichi/poetry-builder:3.9
      volumes:
        - ${{ $GITHUB_WORKSPACE }}:/build
      options: -w /build
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: ls
      - run: ls /build
