name: Publish Docker image
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [variant1, variant2]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            ghcr.io/anyakichi/metadata-test
          flavor: |
            latest=auto
            prefix=aaa
            suffix=
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
