name: Publish Docker image
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [variant1, variant2]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            ghcr.io/anyakichi/metadata-test
          tags: |
            type=schedule,pattern=nightly,suffix=-${{ matrix.tag }},priority=1000
            type=ref,event=branch,suffix=-${{ matrix.tag }},priority=600
            type=ref,event=pr,prefix=pr-,suffix=-${{ matrix.tag }},priority=600
            type=semver,pattern={{version}},suffix=-${{ matrix.tag }}
            type=semver,pattern={{major}}.{{minor}},suffix=-${{ matrix.tag }}
            type=raw,value=${{ matrix.tag }},enable=${{ github.ref == 'refs/heads/main' }}
          flavor: |
            latest=false
      - if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
